steps:

# result app configuration 
- name: 'gcr.io/cloud-builders/docker'
  id: Result-Build
  args:
  - 'build'
  - '-t'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/result:$SHORT_SHA'
  - '-f'
  - 'result/Dockerfile'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Result-Push
  args:
  - 'push'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/result:$SHORT_SHA'


# voting app configuration
- name: 'gcr.io/cloud-builders/docker'
  id: Vote-Build
  args:
  - 'build'
  - '-t'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/voting:$SHORT_SHA'
  - '-f'
  - 'vote/Dockerfile'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  id: Vote-Push 
  args:
    - 'push'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/voting:$SHORT_SHA'


# Pull PostgreSQL  images from docker hub

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'postgres:latest']

