steps:

# Pull voting images from docker hub 
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'pull'
    - 'kodekloud/examplevotingapp_vote:v1'
# tag voting app 
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'kodekloud/examplevotingapp_vote:v1', 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/vote:v1']

# push voting app images to artifact 
- name: 'gcr.io/cloud-builders/docker'
  id: vote-Push 
  args:
    - 'push'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/vote:v1'

###########################################################################
# Result app images pull from docker hub
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'pull'
    - 'kodekloud/examplevotingapp_result:v1'
# tag voting app 
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'kodekloud/examplevotingapp_result:v1', 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/result:v1']

# push voting app images to artifact 
- name: 'gcr.io/cloud-builders/docker'
  id: vote-Push 
  args:
    - 'push'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/result:v1'


###########################################################################
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'pull'
    - 'dockersamples/examplevotingapp_worker'
# tag voting app 
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'dockersamples/examplevotingapp_worker', 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/worker:v1']

# push voting app images to artifact 
- name: 'gcr.io/cloud-builders/docker'
  id: vote-Push 
  args:
    - 'push'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/worker:v1'

#############################################################################

# Pull PostgreSQL  images from docker hub

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'postgres:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'postgres:latest', 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/postgre:v1']  # Replace placeholders  
        # with your desired tag

- name: 'gcr.io/cloud-builders/docker'
  id: postgre-Push 
  args:
    - 'push'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/postgre:v1'

#  Reddis Configuration 
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'redis:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'redis:latest', 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/redis:v1']  # Replace placeholders  
        # with your desired tag

- name: 'gcr.io/cloud-builders/docker'
  id: redis-Push 
  args:
    - 'push'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/microservices/redis:v1'
