apiVersion: apps/v1
kind : Deployment 
metadata:
  name: postgre-pod
 # namespace: voting
  labels:
    app: post 
    env: prod  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
      env: prod  
  template:
    metadata:
      name: postgre-pod
      labels:
        app: post 
        env: prod  
    spec:
      containers:
        - image: asia-east1-docker.pkg.dev/cicd-2024/microservices/postgre:v1
          name:  postgres
          ports:
          - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust